SELECT MAX(case when field_id = 'FC_AGENT_ID' then cast(value as integer) end) AS FC_AGENT_ID
,MAX(case when field_id = 'FC_TLB_EURO' then value end) AS FC_TLB_EURO
,MAX(case when field_id = 'FC_1L_LEV' then value end) AS FC_1L_LEV
,MAX(case when field_id = 'FC_3MNTH_LIBOR' then value end) AS FC_3MNTH_LIBOR
,MAX(case when field_id = 'FC_CLOSING_DT' then value end) AS FC_CLOSING_DT
,MAX(case when field_id = 'FC_COMMIT_DT' then value end) AS FC_COMMIT_DT
,MAX(case when field_id = 'FC_CURR' then value end) AS FC_CURR
,MAX(case when field_id = 'FC_DEAL_ID' then value end) AS FC_DEAL_ID
,MAX(case when field_id = 'FC_EQUITY_OWNERSHIP' then value end) AS FC_EQUITY_OWNERSHIP
,MAX(case when field_id = 'FC_ISSUE_AMOUNT' then value end) AS FC_ISSUE_AMOUNT
,MAX(case when field_id = 'FC_ISSUE_AMOUNT_EURO' then value end) AS FC_ISSUE_AMOUNT_EURO
,MAX(case when field_id = 'FC_ISSUE_AMOUNT_USD' then value end) AS FC_ISSUE_AMOUNT_USD
,MAX(case when field_id = 'FC_ISSUE_COUNTRY' then value end) AS FC_ISSUE_COUNTRY
,MAX(case when field_id = 'FC_ISSUE_ENTITY_NAME' then value end) AS FC_ISSUE_ENTITY_NAME
,MAX(case when field_id = 'FC_ISSUE_MARKET_SECTOR_DESC' then value end) AS FC_ISSUE_MARKET_SECTOR_DESC
,MAX(case when field_id = 'FC_ISSUER_ENTITY_NAME' then value end) AS FC_ISSUER_ENTITY_NAME
,MAX(case when field_id = 'FC_LAUNCH_DATE' then value end) AS FC_LAUNCH_DATE
,MAX(case when field_id = 'FC_MARKET_ISSUANCE' then value end) AS FC_MARKET_ISSUANCE
,MAX(case when field_id = 'FC_MEETING_DT' then value end) AS FC_MEETING_DT
,MAX(case when field_id = 'FC_PERMID' then value end) AS FC_PERMID
,MAX(case when field_id = 'FC_PRICE_TALK' then value end) AS FC_PRICE_TALK
,MAX(case when field_id = 'FC_SPCL_FEATURES' then value end) AS FC_SPCL_FEATURES
,MAX(case when field_id = 'FC_TENOR' then value end) AS FC_TENOR
,MAX(case when field_id = 'FC_TERM_LOANB' then value end) AS FC_TERM_LOANB
,MAX(case when field_id = 'FC_TLB_CCY' then value end) AS FC_TLB_CCY
,MAX(case when field_id = 'FC_TLB_FLOOR' then value end) AS FC_TLB_FLOOR
,MAX(case when field_id = 'FC_TLB_ISSUE_AMOUNT' then value end) AS FC_TLB_ISSUE_AMOUNT
,MAX(case when field_id = 'FC_TLB_MARGIN' then value end) AS FC_TLB_MARGIN
,MAX(case when field_id = 'FC_TLB_OID' then value end) AS FC_TLB_OID
,MAX(case when field_id = 'FC_TLB_PAYMENT' then value end) AS FC_TLB_PAYMENT
,MAX(case when field_id = 'FC_TLB_RATE' then value end) AS FC_TLB_RATE
,MAX(case when field_id = 'FC_TLB_TERM' then value end) AS FC_TLB_TERM
,MAX(case when field_id = 'FC_TRANSACTION_TYPE' then value end) AS FC_TRANSACTION_TYPE
,MAX(case when field_id = 'FC_TTL_LEV' then value end) AS FC_TTL_LEV
,MAX(case when field_id = 'FC_YTM' then value end) AS FC_YTM
,MAX(case when field_id = 'FC_2L' then value end) AS FC_2L
,MAX(case when field_id = 'FC_2L_CCY' then value end) AS FC_2L_CCY
,MAX(case when field_id = 'FC_2L_EURO' then value end) AS FC_2L_EURO
,MAX(case when field_id = 'FC_2L_FLOOR' then value end) AS FC_2L_FLOOR
,MAX(case when field_id = 'FC_2L_ISSUE_AMOUNT' then value end) AS FC_2L_ISSUE_AMOUNT
,MAX(case when field_id = 'FC_2L_MARGIN' then value end) AS FC_2L_MARGIN
,MAX(case when field_id = 'FC_2L_PAYMENT' then value end) AS FC_2L_PAYMENT
,MAX(case when field_id = 'FC_2L_RATE' then value end) AS FC_2L_RATE
,MAX(case when field_id = 'FC_2L_TERM' then value end) AS FC_2L_TERM
,MAX(case when field_id = 'FC_2LOID' then value end) AS FC_2LOID
,MAX(case when field_id = 'FC_2SCRD_LEV' then value end) AS FC_2SCRD_LEV
FROM master.security_attributes m
  join master.securities sec on security_id = sec.fc_sec_id
where field_id in ('FC_AGENT_ID', 'FC_1L_LEV', 'FC_2L', 'FC_2L_CCY', 'FC_2L_EURO', 'FC_2L_FLOOR', 'FC_2L_ISSUE_AMOUNT', 'FC_2L_MARGIN', 'FC_2L_PAYMENT', 'FC_2L_RATE', 'FC_2L_TERM', 'FC_2LOID', 'FC_2SCRD_LEV', 'FC_3MNTH_LIBOR', 'FC_AGENT_ID', 'FC_CLOSING_DT', 'FC_COMMIT_DT', 'FC_CURR', 'FC_DEAL_ID', 'FC_EQUITY_OWNERSHIP', 'FC_ISSUE_AMOUNT', 'FC_ISSUE_AMOUNT_EURO', 'FC_ISSUE_AMOUNT_USD', 'FC_ISSUE_COUNTRY', 'FC_ISSUE_ENTITY_NAME', 'FC_ISSUE_MARKET_SECTOR_DESC', 'FC_ISSUER_ENTITY_NAME', 'FC_LAUNCH_DATE', 'FC_MARKET_ISSUANCE', 'FC_MEETING_DT', 'FC_PERMID', 'FC_PRICE_TALK', 'FC_SPCL_FEATURES', 'FC_TENOR', 'FC_TERM_LOANB', 'FC_TLB_CCY', 'FC_TLB_EURO', 'FC_TLB_FLOOR', 'FC_TLB_ISSUE_AMOUNT', 'FC_TLB_MARGIN', 'FC_TLB_OID', 'FC_TLB_PAYMENT', 'FC_TLB_RATE', 'FC_TLB_TERM', 'FC_TRANSACTION_TYPE', 'FC_TTL_LEV', 'FC_YTM')
and m.source_id = 7
group by security_id order by FC_AGENT_ID;