SELECT MAX(case when field_id = 'FC_AGENT_ID' then value end) AS FC_AGENT_ID
,MAX(case when field_id = 'FC_LFYHYID' then value end) AS FC_LFYHYID
,MAX(case when field_id = 'FC_1ST_CALL_DT' then value end) AS FC_1ST_CALL_DT
,MAX(case when field_id = 'FC_1ST_CALL_PRICE' then value end) AS FC_1ST_CALL_PRICE
,MAX(case when field_id = 'FC_LAUNCH_DATE' then value end) AS FC_LAUNCH_DATE
,MAX(case when field_id = 'FC_TRANSACTION_TYPE' then value end) AS FC_TRANSACTION_TYPE
,MAX(case when field_id = 'FC_BOND_TYPE' then value end) AS FC_BOND_TYPE
,MAX(case when field_id = 'FC_CALL_PERCENTAGE' then value end) AS FC_CALL_PERCENTAGE
,MAX(case when field_id = 'FC_CALL_PROTECTION' then value end) AS FC_CALL_PROTECTION
,MAX(case when field_id = 'FC_CALL_PRIM' then value end) AS FC_CALL_PRIM
,MAX(case when field_id = 'FC_CALL_SCHEDULE' then value end) AS FC_CALL_SCHEDULE
,MAX(case when field_id = 'FC_CASH_PIK' then value end) AS FC_CASH_PIK
,MAX(case when field_id = 'FC_CHANGE_OF_CONTROL' then value end) AS FC_CHANGE_OF_CONTROL
,MAX(case when field_id = 'FC_CHANGE_ON_BREAK' then value end) AS FC_CHANGE_ON_BREAK
,MAX(case when field_id = 'FC_CONCURRENT_LOAN_ID' then value end) AS FC_CONCURRENT_LOAN_ID
,MAX(case when field_id = 'FC_DAYS_IN_MARKET' then value end) AS FC_DAYS_IN_MARKET
,MAX(case when field_id = 'FC_DEBUT' then value end) AS FC_DEBUT
,MAX(case when field_id = 'FC_DESCRIPTION' then value end) AS FC_DESCRIPTION
,MAX(case when field_id = 'FC_FNL_DOC_SCR' then value end) AS FC_FNL_DOC_SCR
,MAX(case when field_id = 'FC_EBITDA' then value end) AS FC_EBITDA
,MAX(case when field_id = 'FC_EQUITY_CLAW_PERCENTAGE' then value end) AS FC_EQUITY_CLAW_PERCENTAGE
,MAX(case when field_id = 'FC_EQUITY_CLAW_PRICE' then value end) AS FC_EQUITY_CLAW_PRICE
,MAX(case when field_id = 'FC_EQUITY_CLAW_YEARS' then value end) AS FC_EQUITY_CLAW_YEARS
,MAX(case when field_id = 'FC_EQUITY_PERCENTAGE' then value end) AS FC_EQUITY_PERCENTAGE
,MAX(case when field_id = 'FC_FIXED_FLOATING' then value end) AS FC_FIXED_FLOATING
,MAX(case when field_id = 'FC_INDUSTRY' then value end) AS FC_INDUSTRY
,MAX(case when field_id = 'FC_INDUSTRY_DESCRIPTION' then value end) AS FC_INDUSTRY_DESCRIPTION
,MAX(case when field_id = 'FC_ISSUE_AMOUNT' then value end) AS FC_ISSUE_AMOUNT
,MAX(case when field_id = 'FC_ISSUE_COUPON_RATE' then value end) AS FC_ISSUE_COUPON_RATE
,MAX(case when field_id = 'FC_ISSUE_PRICE_FNL' then value end) AS FC_ISSUE_PRICE_FNL
,MAX(case when field_id = 'FC_ISSUE_PRICE_PRLM' then value end) AS FC_ISSUE_PRICE_PRLM
,MAX(case when field_id = 'FC_ISSUER_ENTITY_NAME' then value end) AS FC_ISSUER_ENTITY_NAME
,MAX(case when field_id = 'FC_SCRD_LEV' then value end) AS FC_SCRD_LEV
,MAX(case when field_id = 'FC_TTL_LEV' then value end) AS FC_TTL_LEV
,MAX(case when field_id = 'FC_MARKET_ISSUANCE' then value end) AS FC_MARKET_ISSUANCE
,MAX(case when field_id = 'FC_MATURITY_DATE' then value end) AS FC_MATURITY_DATE
,MAX(case when field_id = 'FC_NC_YEARS' then value end) AS FC_NC_YEARS
,MAX(case when field_id = 'FC_NOTES' then value end) AS FC_NOTES
,MAX(case when field_id = 'FC_ISSUE_CUSIP' then value end) AS FC_ISSUE_CUSIP
,MAX(case when field_id = 'FC_OWNERSHIP' then value end) AS FC_OWNERSHIP
,MAX(case when field_id = 'FC_PERMID' then value end) AS FC_PERMID
,MAX(case when field_id = 'FC_PERMNAME' then value end) AS FC_PERMNAME
,MAX(case when field_id = 'FC_PRICING_DT' then value end) AS FC_PRICING_DT
,MAX(case when field_id = 'FC_PURPOSE' then value end) AS FC_PURPOSE
,MAX(case when field_id = 'FC_CMNT_PURPOSE' then value end) AS FC_CMNT_PURPOSE
,MAX(case when field_id = 'FC_ROAD_SHOW_DATE' then value end) AS FC_ROAD_SHOW_DATE
,MAX(case when field_id = 'FC_SECONDARY' then value end) AS FC_SECONDARY
,MAX(case when field_id = 'FC_SENIORITY' then value end) AS FC_SENIORITY
,MAX(case when field_id = 'FC_SIZE_PRLM' then value end) AS FC_SIZE_PRLM
,MAX(case when field_id = 'FC_SPECIAL_CALL' then value end) AS FC_SPECIAL_CALL
,MAX(case when field_id = 'FC_SPREAD' then value end) AS FC_SPREAD
,MAX(case when field_id = 'FC_LIBOR_SPREAD' then value end) AS FC_LIBOR_SPREAD
,MAX(case when field_id = 'FC_TALK_PRLM' then value end) AS FC_TALK_PRLM
,MAX(case when field_id = 'FC_TARGET' then value end) AS FC_TARGET
,MAX(case when field_id = 'FC_TENOR' then value end) AS FC_TENOR
,MAX(case when field_id = 'FC_TRANSACTION' then value end) AS FC_TRANSACTION
,MAX(case when field_id = 'FC_UNDERWRITER' then value end) AS FC_UNDERWRITER
,MAX(case when field_id = 'FC_YTM' then value end) AS FC_YTM
FROM master.security_attributes m
       join master.securities sec on security_id = sec.fc_sec_id
where field_id in ('FC_1ST_CALL_DT', 'FC_1ST_CALL_PRICE', 'FC_AGENT_ID', 'FC_LAUNCH_DATE', 'FC_TRANSACTION_TYPE', 'FC_BOND_TYPE', 'FC_CALL_PERCENTAGE', 'FC_CALL_PROTECTION', 'FC_CALL_PRIM', 'FC_CALL_SCHEDULE', 'FC_CASH_PIK', 'FC_CHANGE_OF_CONTROL', 'FC_CHANGE_ON_BREAK', 'FC_CONCURRENT_LOAN_ID', 'FC_DAYS_IN_MARKET', 'FC_DEBUT', 'FC_DESCRIPTION', 'FC_FNL_DOC_SCR', 'FC_EBITDA', 'FC_EQUITY_CLAW_PERCENTAGE', 'FC_EQUITY_CLAW_PRICE', 'FC_EQUITY_CLAW_YEARS', 'FC_EQUITY_PERCENTAGE', 'FC_FIXED_FLOATING', 'FC_INDUSTRY', 'FC_INDUSTRY_DESCRIPTION', 'FC_ISSUE_AMOUNT', 'FC_ISSUE_COUPON_RATE', 'FC_ISSUE_PRICE_FNL', 'FC_ISSUE_PRICE_PRLM', 'FC_ISSUER_ENTITY_NAME', 'FC_SCRD_LEV', 'FC_TTL_LEV', 'FC_LFYHYID', 'FC_MARKET_ISSUANCE', 'FC_MATURITY_DATE', 'FC_NC_YEARS', 'FC_NOTES', 'FC_ISSUE_CUSIP', 'FC_OWNERSHIP', 'FC_PERMID', 'FC_PERMNAME', 'FC_PRICING_DT', 'FC_PURPOSE', 'FC_CMNT_PURPOSE', 'FC_ROAD_SHOW_DATE', 'FC_SECONDARY', 'FC_SENIORITY', 'FC_SIZE_PRLM', 'FC_SPECIAL_CALL', 'FC_SPREAD', 'FC_LIBOR_SPREAD', 'FC_TALK_PRLM', 'FC_TARGET', 'FC_TENOR', 'FC_TRANSACTION', 'FC_UNDERWRITER', 'FC_YTM')
and m.source_id = 6
group by security_id order by FC_LFYHYID;